### PR TITLE
Switched CI to GH Actions

### PR DESCRIPTION
**Pull request by slawekjaranowski**
fix: #15

- gradle wrapper was refreshed
- it is copied from mockito
- single job was moved to separate stage - verify
- check reproducibility require change in build - will be done by issue #18 
- release stage also require change in build - will be done by issue #14

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Hello. Is this a copy of https://github.com/mockito/mockito/tree/release/3.x/.github/workflows ? is anything extra here? Can you list it in the PR description?

**Comment by slawekjaranowski** [comment]
- it is copied from mockito
 - single job was moved to separate stage - verify
 - check reproducibility require change in build, so will be done as separate task - now is commented
 - release stage also require change in build - will be done by issue #14

**Review by skabashnyuk — APPROVED** [review]

**Comment by slawekjaranowski** [comment]
@mockitoguy @skabashnyuk Kindly reminder about it.
I will take care about next issues.

**Comment by skabashnyuk** [comment]
@slawekjaranowski  May I ask you to take a look at build results? https://github.com/mockito/mockito-testng/actions/runs/384758526

**Comment by slawekjaranowski** [comment]
Please re-run github action problem ... on `build (11, windows-latest)`
 
```
Error: Exception in thread "main" java.io.IOException: Downloading from https://services.gradle.org/distributions/gradle-6.7.1-bin.zip failed: timeout
```

https://github.com/mockito/mockito-testng/runs/1457653160?check_suite_focus=true

**Pull request merged**
